version: '2'
services:
    radcasemanager-app:
        image: radcasemanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://radcasemanager-postgresql:5432/radCaseManager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    radcasemanager-postgresql:
        extends:
            file: postgresql.yml
            service: radcasemanager-postgresql
